name: album_app
description: A Flutter app to fetch and display albums and photos from JSONPlaceholder API.
version: 1.0.0
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^14.2.0
  http: ^1.1.0
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true